---
repos:
  - repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks:
      - id: standard
        args: [--fix]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Check for latest version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
