# Minimal monitor@ configuration that renders a simple dashboard.

site:
  name: "monitor@"
  title: "System Monitor"
  base_url: "http://localhost:6161"

paths:
  data: "data/"                 # relative to webroot (www/)
  img: "img/"                   # use absolute path for ~/.config/monitor@/img
  favicon: "img/favicon.ico"

widgets:
  enabled:                      # provides order and visibility
    - metrics                   # www/widgets/* for available widgets
    - wiki
  metrics:                      # temperature, cpu, memory, disk
    name: "System Metrics"
  wiki:                         # load README.md if doc not specified
    name: "Notes & Links"
    display: open
    doc: ""
    #doc: /home/__user__/documents/about.md

privacy:                        # toggle, for screenshots
  mask_ips: true
  replacements: {}

reminders:
  nudges: [14, 7]
  urgents: [3, 1, 0]
  time: "23:55"

services: {}

pushover:
  key: ""
  token: ""